using System;
using System.Collections.Generic;
using System.Text;
public class MsgIDDefineDic
{
	public const int LOGIN_MESSAGE_CMSGACCOUNTLOGINREQUEST = 10001; 
	public const int LOGIN_MESSAGE_CMSGACCOUNTLOGINRESPONSE = 10002; 
	public const int LOGIN_MESSAGE_CMSGACCOUNTREGISTREQUEST = 10003; 
	public const int LOGIN_MESSAGE_CMSGACCOUNTREGISTRESPONSE = 10004; 
	public const int ROLE_MESSAGE_CMSGROLELISTREQUEST = 10101; 
	public const int ROLE_MESSAGE_CMSGROLELISTRESPONSE = 10102; 
	public const int ROLE_MESSAGE_CMSGROLECREATEREQUEST = 10103; 
	public const int ROLE_MESSAGE_CMSGROLECREATERESPONSE = 10104; 
}
